server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boardtestdb
    driver-class-name: org.postgresql.Driver
    username: 'boardtest'
    password: '00'

  security:
    user:
      name: username
      password: passw0rd

  messages:
    basename: messages

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org.springframework: debug

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"
