server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boardtestdb
    driver-class-name: org.postgresql.Driver
    username: 'boardtest'
    password: '00'

  messages:
    basename: messages


#logging:
#  level:
#    org.springframework: debug

